parameters:
  api_platform.pomm.collection.pagination:
    enabled: '%api_platform.collection.pagination.enabled%'
    client_enabled: '%api_platform.collection.pagination.client_enabled%'
    client_items_per_pages: '%api_platform.collection.pagination.client_items_per_page%'
    items_per_page: '%api_platform.collection.pagination.items_per_page%'
    enabled_parameter_name: '%api_platform.collection.pagination.enabled_parameter_name%'
    items_per_page_parameter_name: '%api_platform.collection.pagination.items_per_page_parameter_name%'
    maximum_items_per_page: '%api_platform.collection.pagination.maximum_items_per_page%'
    page_parameter_name: '%api_platform.collection.pagination.page_parameter_name%'

  api_platform.pomm.collection.order:
    order_parameter_name: '%api_platform.collection.order_parameter_name%'

services:
  api_platform.pomm.collection_data_provider:
    class: 'PommProject\ApiPlatform\CollectionDataProvider'
    arguments:
      - '@pomm'
      - '@request_stack'
      - '%api_platform.pomm.collection.pagination%'
      - '%api_platform.pomm.collection.order%'
    tags:
      - { name: 'api_platform.collection_data_provider' }

  api_platform.pomm.item_data_provider:
    class: 'PommProject\ApiPlatform\ItemDataProvider'
    arguments: ['@pomm']
    tags:
      - { name: 'api_platform.item_data_provider' }

  api_platform.pomm.listener.view.write:
    class: 'PommProject\ApiPlatform\WriteListener'
    arguments: ['@pomm']
    tags:
      - { name: 'kernel.event_listener', event: 'kernel.view', method: 'onKernelView', priority: 32 }
